server {
    listen 80;

    server_name uno-game-dev.org www.uno-game-dev.org;
    # Serve the Let's Encrypt ACME challenge for SSL certificate
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
        # Logging for troubleshooting
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    
    }

      

    
}
server {
    listen 443 ssl;

    server_name uno-game-dev.org www.uno-game-dev.org;
    ssl_certificate /etc/letsencrypt/live/uno-game-dev.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/uno-game-dev.org/privkey.pem;
    # Serve static files
     location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
        # Logging for troubleshooting
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    
    }
    
}
